feat: adding verification to avoid multiple orders within 7 days
SocialGouv/Tumeplay pull request #11
Opened 2021-06-30 10:12 UTC by BrianRid

2021-06-30 16:11 UTC, ClementNumericite requested changes

2021-06-30 16:11 UTC, ClementNumericite commented on tumeplay-app/src/screens/components/tunnel/OrderNotAllowedModal.js
> +  console.log("Show MODAL", showModal)
remove console log

2021-06-30 16:11 UTC, ClementNumericite commented on tumeplay-app/src/screens/components/header/CustomHeaderRight.js
> +    // 1. Get userlastOrder from localhost
remove comments

2021-07-01 08:20 UTC, BrianRid commented on tumeplay-app/src/screens/components/header/CustomHeaderRight.js
> +    // 1. Get userlastOrder from localhost
Done

2021-07-01 08:36 UTC, merged