Feat/landing integration
SocialGouv/Tumeplay pull request #26
Opened 2021-07-12 15:27 UTC by BrianRid

2021-07-12 16:59 UTC, ClementNumericite requested changes

2021-07-12 16:59 UTC, ClementNumericite commented on tumeplay-app/environnements/env.dev.guyane
> +REACT_APP_OTHER_ZONE_URL=http://localhost:3001/?zone_choice=true
pas bon ça, pourquoi avoir enlever "+ param" ligne 14 de LandingPage.js ?

2021-07-12 16:59 UTC, ClementNumericite commented on tumeplay-app/environnements/env.dev.metropole
> +REACT_APP_OTHER_ZONE_URL=http://localhost:3002/?zone_choice=true
pareil

2021-07-13 08:26 UTC, BrianRid commented on tumeplay-app/environnements/env.dev.guyane
> +REACT_APP_OTHER_ZONE_URL=http://localhost:3001/?zone_choice=true
J'ai remis une variable param que je passe directement dans le composant landing page

2021-07-13 08:32 UTC, merged